### PR TITLE
V1/170 routing fix

### LINKED ISSUE #170: Routing issues
poll result should be visible for every user that belongs to a presentation

missing choices index and update routes

### PR DESCRIPTION
**Pull request by kayoumido**

### CODE REVIEW

File: src/app/Http/Middleware/CheckChoiceRole.php [hunk 1]
```diff
@@ -16,9 +16,9 @@ class CheckChoiceRole
      * @param  \Closure  $next
      * @return mixed
      */
-    public function handle($request, Closure $next, ...$roles)
+    public function handle($request, Closure $next, $roles)
     {
-        if (!check_role(Auth::user()->presentations()->where('id', $request->choice->poll->presentation->id)->first(), $roles)) {
+        if (!check_role(Auth::user()->presentations()->where('id', $request->choice->poll->presentation->id)->first(), explode('|', $roles))) {
```
Comment (fabio10000) [inline src/app/Http/Middleware/CheckChoiceRole.php]: `...$roles` like in java is to be able to do a call with variable nb of params ex `myFunction(role1, role2, role3, etc.)`
also Laravel conventions for calling function with params c.f validators are `myFunction:param1,param2|myOtherFunction` so you don't want to force it to use a `|` to séparate your params as it means by Laravel that you are waiting another function.
Not sure if it's understandable, don't hesitate to ask questions

File: src/app/Http/Middleware/CheckPollRole.php [hunk 2]
```diff
@@ -16,10 +16,9 @@ class CheckPollRole
      * @param  \Closure  $next
      * @return mixed
      */
-    public function handle($request, Closure $next, ...$roles)
+    public function handle($request, Closure $next, $roles)
     {
-
-        if (!check_role(Auth::user()->presentations()->where('id', $request->poll->presentation->id)->first(), $roles)) {
+        if (!check_role(Auth::user()->presentations()->where('id', $request->poll->presentation->id)->first(), explode('|', $roles))) {
```
Comment (fabio10000) [inline src/app/Http/Middleware/CheckPollRole.php]: same problem with `$roles`

File: src/app/Http/Middleware/CheckPresentationRole.php [hunk 3]
```diff
@@ -17,9 +17,9 @@ class CheckPresentationRole
      * @param  \Closure  $next
      * @return mixed
      */
-    public function handle($request, Closure $next, ... $roles)
+    public function handle($request, Closure $next, $roles)
     {
-        if (!check_role(Auth::user()->presentations()->where('id', $request->presentation->id)->first(), $roles)) {
+        if (!check_role(Auth::user()->presentations()->where('id', $request->presentation->id)->first(), explode('|', $roles))) {
```
Comment (fabio10000) [inline src/app/Http/Middleware/CheckPresentationRole.php]: same problem with `$roles`

File: src/routes/api.php [hunk 4]
```diff
@@ -51,7 +51,13 @@
             Route::apiResource('polls', 'API\PollController')->only(['update'])->shallow();
             Route::put('polls/{poll}/publish', 'API\PollController@publish')->name('polls.publish');
             Route::get('polls/{poll}/results', 'API\PollController@results')->name('polls.results');
-            Route::apiResource('polls.choices', 'API\ChoiceController')->only(['store'])->shallow();
+            Route::apiResource('polls.choices', 'API\ChoiceController')->only(['store', 'update'])->shallow();
+        });
+
+        Route::apiResource('polls.choices', 'API\ChoiceController')->only(['index'])->shallow();
+
+        Route::middleware(['poll.role:' . App\User\Role::PRESENTER() . '|' . App\User\Role::ATENDEE()])->group(function () {
```
Comment (fabio10000) [inline src/routes/api.php]: params should be separed by a `,` and not a `|` c.f previous comment

**Review by fabio10000 — CHANGES_REQUESTED** [review]

File: src/app/Http/Middleware/CheckChoiceRole.php (hunk 1 above)
Comment (kayoumido) [reply src/app/Http/Middleware/CheckChoiceRole.php]: I don't want multiple variables, I want an array, otherwise the helper won't work. I didn't find any other way to pass an array to the middleware

File: src/app/Http/Middleware/CheckPollRole.php (hunk 2 above)
Comment (kayoumido) [reply src/app/Http/Middleware/CheckPollRole.php]: same answer

File: src/app/Http/Middleware/CheckPresentationRole.php (hunk 3 above)
Comment (kayoumido) [reply src/app/Http/Middleware/CheckPresentationRole.php]: same answer

File: src/routes/api.php (hunk 4 above)
Comment (kayoumido) [reply src/routes/api.php]: same answer

**Review by Serphentas — APPROVED** [review]
Tested:
- [x] Get results as attendee, authorized
- [x] Get choice index, authorized

**Review by fabio10000 — APPROVED** [review]
